Refactor module to use chain-registry for defaults based on chain-name
osmosis-labs/infrastructure pull request #5
Opened 2022-01-01 08:01 UTC by UnityChaos

Closes #4 

Implemented a basic setup of this idea, which uses the `chain-name` variable and https://github.com/cosmos/chain-registry to set default variables and parameters which can be overridden by manually setting terraform variables.

I also simplified the setup scripts in the module, to just install the chosen node software and initialize a genesis with a single validator. Would like to eventually extend that for other setups  (see #3), but I think that should be sorted out separately.

I'm still new to IAC, so feel free to advise if some of what I'm doing is hacky or non-standard

2022-01-01 08:22 UTC, ValarDragon commented
As a headsup, we will be changing app.toml for Osmosis, and config.toml defaults, so we may still need to make osmosis start scripts. (But perhaps it can invoke the general one, and then adapt things after?)

2022-01-02 10:59 UTC, nikever requested changes
LGTM. Great work. 
I like the idea of generalizing the module using the `chain-registry`

I have added some suggestions, more cosmetic changes than substantial ones.

One thing, I have used [terraform-docs](https://github.com/terraform-docs/terraform-docs) to automatically generate the documentation for the terraform module. Could you use it to update the module documentation? Sorry it wasn't really documented

2022-01-02 10:59 UTC, nikever commented on .gitignore
> +*terraform*
I think this is too wide. The main goal was to block any `.terraform` folder. I would change it to `**/.terraform/`

2022-01-02 10:59 UTC, nikever commented on modules/digital-ocean/cosmos-sdk-node/node.tf
> +  username = "terraform"
Instead of `terraform`, maybe use something like `cosmos`?

2022-01-02 10:59 UTC, nikever commented on README.md
> +| `Cosmos-SDK Node` | DO       | Setup Cosmos-SDK node(s) | [link](./modules/digital-ocean/cosmos-sdk-node) |
Could you format the table? 
You could use: http://markdowntable.com/ or there are various extensions for common IDEs

2022-01-02 10:59 UTC, nikever commented on examples/do-cosmos-sdk-node/README.md
> +ssh -i key terraform@159.203.80.187
As above, Instead of `terraform`, maybe use something like `cosmos`?

2022-06-22 16:48 UTC, closed without merging